version: "3"

vars:
  SOLUTION: "ASPCleanArchitecture.sln"
  API_PROJECT: "Web.API/Web.API.csproj"
  INFRA_PROJECT: "Infrastructure"
  MIGRATIONS_DIR: "Data/Migrations"

  # Tests
  TEST_DOMAIN: "Tests/Domain.UnitTests"
  TEST_APPLICATION: "Tests/Application.UnitTests"
  TEST_INTEGRATION: "Tests/Web.API.IntegrationTests"

tasks:
  default:
    desc: List all commands
    cmd: task --list-all
    silent: true

  # ============================================================================
  # .NET Commands
  # ============================================================================

  restore:
    desc: Restore NuGet packages
    aliases: [r]
    cmd: dotnet restore {{.CLI_ARGS}}

  build:
    desc: Build the solution
    aliases: [b]
    cmd: dotnet build {{.CLI_ARGS}}

  build:release:
    desc: Build for production
    aliases: [b:r, b:prod]
    cmd: dotnet build --configuration Release {{.CLI_ARGS}}

  clean:
    desc: Clean build outputs
    aliases: [c]
    cmd: dotnet clean {{.CLI_ARGS}}

  run:
    desc: Run the API
    aliases: [start, serve]
    cmd: dotnet run --project {{.API_PROJECT}} {{.CLI_ARGS}}

  watch:
    desc: Run with hot reload
    aliases: [dev, w]
    cmd: dotnet watch --project {{.API_PROJECT}} {{.CLI_ARGS}}

  format:
    desc: Format code
    aliases: [fmt]
    cmd: dotnet format {{.CLI_ARGS}}

  format:check:
    desc: Check code formatting
    aliases: [fmt:check]
    cmd: dotnet format --verify-no-changes {{.CLI_ARGS}}

  # ============================================================================
  # Testing
  # ============================================================================

  test:
    desc: Run all tests
    aliases: [t]
    cmd: dotnet test {{.CLI_ARGS}}

  test:unit:
    desc: Run unit tests only
    aliases: [t:u]
    deps: [test:domain, test:application]

  test:domain:
    desc: Run Domain unit tests
    aliases: [t:d]
    cmd: dotnet test {{.TEST_DOMAIN}} {{.CLI_ARGS}}

  test:application:
    desc: Run Application unit tests
    aliases: [t:a]
    cmd: dotnet test {{.TEST_APPLICATION}} {{.CLI_ARGS}}

  test:integration:
    desc: Run integration tests
    aliases: [t:i]
    cmd: dotnet test {{.TEST_INTEGRATION}} {{.CLI_ARGS}}

  test:coverage:
    desc: Run tests with coverage
    aliases: [t:c]
    cmd: dotnet test --collect:"XPlat Code Coverage" {{.CLI_ARGS}}

  # ============================================================================
  # EF Core Migrations
  # ============================================================================

  ef:
    desc: Run dotnet ef command
    cmd: dotnet ef {{.CLI_ARGS}} --project {{.INFRA_PROJECT}} --startup-project Web.API

  migration:add:
    desc: Create a new migration
    aliases: [ef:m:add, m:add]
    cmd: dotnet ef migrations add {{.CLI_ARGS}} --project {{.INFRA_PROJECT}} --startup-project Web.API --output-dir {{.MIGRATIONS_DIR}}

  migration:remove:
    desc: Remove last migration
    aliases: [ef:m:remove, m:remove]
    cmd: dotnet ef migrations remove --project {{.INFRA_PROJECT}} --startup-project Web.API

  migration:list:
    desc: List migrations
    aliases: [ef:m:list, m:list]
    cmd: dotnet ef migrations list --project {{.INFRA_PROJECT}} --startup-project Web.API

  db:update:
    desc: Apply pending migrations
    aliases: [ef:d:u, migration:apply, m:apply]
    cmd: dotnet ef database update --project {{.INFRA_PROJECT}} --startup-project Web.API {{.CLI_ARGS}}

  db:drop:
    desc: Drop the database
    aliases: [ef:d:drop]
    cmd: dotnet ef database drop --project {{.INFRA_PROJECT}} --startup-project Web.API --force

  # ============================================================================
  # Docker
  # ============================================================================

  docker:up:
    desc: Start containers (with dev proxy & caching)
    aliases: [up, d:up]
    cmd: docker compose --profile dev --profile caching up --build -d {{.CLI_ARGS}}

  docker:up:minimal:
    desc: Start containers (API + DB only)
    aliases: [up:min]
    cmd: docker compose up --build -d {{.CLI_ARGS}}

  docker:down:
    desc: Stop containers
    aliases: [down, d:down]
    cmd: docker compose down {{.CLI_ARGS}}

  docker:reset:
    desc: Stop containers and remove volumes
    aliases: [d:reset]
    cmd: docker compose down -v {{.CLI_ARGS}}

  docker:logs:
    desc: View container logs
    aliases: [logs, d:logs]
    cmd: docker compose logs -f {{.CLI_ARGS}}

  docker:logs:api:
    desc: View API logs
    aliases: [logs:api]
    cmd: docker compose logs -f api

  docker:ps:
    desc: List running containers
    aliases: [ps, d:ps]
    cmd: docker compose ps

  docker:build:
    desc: Build Docker image
    aliases: [d:build]
    cmd: docker build -t aspcleanarchitecture -f Web.API/Dockerfile .

  # ============================================================================
  # CI/CD Tasks (for GitHub Actions)
  # ============================================================================

  ci:restore:
    desc: "[CI] Restore dependencies"
    cmd: dotnet restore

  ci:build:
    desc: "[CI] Build for CI"
    cmd: dotnet build --no-restore --configuration Release

  ci:test:unit:
    desc: "[CI] Run unit tests"
    cmds:
      - dotnet test {{.TEST_DOMAIN}} --no-build --configuration Release --verbosity normal
      - dotnet test {{.TEST_APPLICATION}} --no-build --configuration Release --verbosity normal

  ci:test:integration:
    desc: "[CI] Run integration tests"
    cmd: dotnet test {{.TEST_INTEGRATION}} --no-build --configuration Release --verbosity normal

  ci:format:
    desc: "[CI] Check formatting"
    cmd: dotnet format --verify-no-changes

  # ============================================================================
  # Utilities
  # ============================================================================

  example:remove:
    desc: Remove Products example from solution
    platforms: [linux, darwin]
    cmd: ./scripts/remove-products-example.sh

  example:remove:windows:
    desc: Remove Products example from solution (Windows)
    platforms: [windows]
    cmd: powershell -ExecutionPolicy Bypass -File scripts/remove-products-example.ps1

  info:
    desc: Show environment info
    cmds:
      - dotnet --info
      - echo "---"
      - docker --version
      - docker compose version
    silent: true
