version: "3"

dotenv: [".env"]

vars:
  SOLUTION: "ASPCleanArchitecture.sln"
  API_PROJECT: "Web.API/Web.API.csproj"
  INFRA_PROJECT: "Infrastructure"
  MIGRATIONS_DIR: "Data/Migrations"

#if (IncludeTests)
  # Tests
  TEST_DOMAIN: "Tests/Domain.UnitTests"
  TEST_APPLICATION: "Tests/Application.UnitTests"
  TEST_INTEGRATION: "Tests/Web.API.IntegrationTests"
#endif

  # Deploy
  PUBLISH_DIR: "./publish"
  DEPLOY_RUNTIME: '{{default "linux-x64" .DEPLOY_RUNTIME}}'
  PROJECT_NAME: '{{default "aspcleanarchitecture" .PROJECT_NAME}}'

tasks:
  default:
    desc: List all commands
    cmd: task --list-all
    silent: true

  # ============================================================================
  # .NET Commands
  # ============================================================================

  restore:
    desc: Restore NuGet packages
    aliases: [r]
    cmd: dotnet restore {{.CLI_ARGS}}

  build:
    desc: Build the solution
    aliases: [b]
    cmd: dotnet build {{.CLI_ARGS}}

  build:release:
    desc: Build for production
    aliases: [b:r, b:prod]
    cmd: dotnet build --configuration Release {{.CLI_ARGS}}

  clean:
    desc: Clean build outputs
    aliases: [c]
    cmd: dotnet clean {{.CLI_ARGS}}

  run:
    desc: Run the API
    aliases: [start, serve]
    cmd: dotnet run --project {{.API_PROJECT}} {{.CLI_ARGS}}

  watch:
    desc: Run with hot reload
    aliases: [dev, w]
    cmd: dotnet watch --project {{.API_PROJECT}} {{.CLI_ARGS}}

  format:
    desc: Format code
    aliases: [fmt]
    cmd: dotnet format {{.CLI_ARGS}}

  format:check:
    desc: Check code formatting
    aliases: [fmt:check]
    cmd: dotnet format --verify-no-changes {{.CLI_ARGS}}

#if (IncludeTests)
  # ============================================================================
  # Testing
  # ============================================================================

  test:
    desc: Run all tests
    aliases: [t]
    cmd: dotnet test {{.CLI_ARGS}}

  test:unit:
    desc: Run unit tests only
    aliases: [t:u]
    deps: [test:domain, test:application]

  test:domain:
    desc: Run Domain unit tests
    aliases: [t:d]
    cmd: dotnet test {{.TEST_DOMAIN}} {{.CLI_ARGS}}

  test:application:
    desc: Run Application unit tests
    aliases: [t:a]
    cmd: dotnet test {{.TEST_APPLICATION}} {{.CLI_ARGS}}

  test:integration:
    desc: Run integration tests
    aliases: [t:i]
    cmd: dotnet test {{.TEST_INTEGRATION}} {{.CLI_ARGS}}

  test:coverage:
    desc: Run tests with coverage
    aliases: [t:c]
    cmd: dotnet test --collect:"XPlat Code Coverage" {{.CLI_ARGS}}
#endif

  # ============================================================================
  # EF Core Migrations
  # ============================================================================

  ef:
    desc: Run dotnet ef command
    cmd: dotnet ef {{.CLI_ARGS}} --project {{.INFRA_PROJECT}} --startup-project Web.API

  migration:add:
    desc: Create a new migration
    aliases: [ef:m:add, m:add]
    cmd: dotnet ef migrations add {{.CLI_ARGS}} --project {{.INFRA_PROJECT}} --startup-project Web.API --output-dir {{.MIGRATIONS_DIR}}

  migration:remove:
    desc: Remove last migration
    aliases: [ef:m:remove, m:remove]
    cmd: dotnet ef migrations remove --project {{.INFRA_PROJECT}} --startup-project Web.API

  migration:list:
    desc: List migrations
    aliases: [ef:m:list, m:list]
    cmd: dotnet ef migrations list --project {{.INFRA_PROJECT}} --startup-project Web.API

  db:update:
    desc: Apply pending migrations
    aliases: [ef:d:u, migration:apply, m:apply]
    cmd: dotnet ef database update --project {{.INFRA_PROJECT}} --startup-project Web.API {{.CLI_ARGS}}

  db:drop:
    desc: Drop the database
    aliases: [ef:d:drop]
    cmd: dotnet ef database drop --project {{.INFRA_PROJECT}} --startup-project Web.API --force

  db:shell:
    desc: Open PostgreSQL shell
    cmd: docker compose exec db psql -U postgres -d ${POSTGRES_DB:-app}

#if (IncludeDocker)
  # ============================================================================
  # Docker Development
  # ============================================================================

  docker:up:
    desc: Start dev environment (DB on Windows/Mac, full stack on Linux)
    aliases: [up]
    cmds:
      - task: '{{if eq OS "windows"}}docker:up:infra{{else if eq OS "darwin"}}docker:up:infra{{else}}docker:up:full{{end}}'

  docker:up:infra:
    desc: Start infrastructure only (DB, Traefik)
    aliases: [d:up:infra]
    cmd: docker compose up -d

  docker:up:full:
    desc: Start full dev environment (infrastructure + API container)
    aliases: [d:up:full]
    cmd: docker compose --profile full up -d

  docker:down:
    desc: Stop dev environment
    aliases: [down]
    cmd: docker compose --profile full down

  docker:logs:
    desc: View dev logs
    aliases: [logs]
    cmd: docker compose --profile full logs -f {{.CLI_ARGS}}

  docker:watch:
    desc: Start full dev with attached logs (see hot-reload output)
    cmd: docker compose --profile full up

  docker:clean:
    desc: Remove all containers and volumes
    cmd: docker compose --profile full --profile prod down -v

  docker:rebuild:
    desc: Rebuild and restart containers
    cmds:
      - task: '{{if eq OS "windows"}}docker:rebuild:infra{{else if eq OS "darwin"}}docker:rebuild:infra{{else}}docker:rebuild:full{{end}}'

  docker:rebuild:infra:
    desc: Rebuild infrastructure only
    cmd: docker compose up --build -d

  docker:rebuild:full:
    desc: Rebuild full dev environment
    cmd: docker compose --profile full up --build -d

  # ============================================================================
  # Certificate Setup (mkcert)
  # ============================================================================

  certs:setup:
    desc: Generate mkcert certificates for local HTTPS
    platforms: [linux, darwin]
    cmd: ./scripts/setup-certs.sh

  certs:setup:windows:
    desc: Generate mkcert certificates for local HTTPS (Windows)
    platforms: [windows]
    cmd: powershell -ExecutionPolicy Bypass -File scripts/setup-certs.ps1

  # ============================================================================
  # Production (Docker Compose)
  # ============================================================================

  prod:up:
    desc: Start production containers
    aliases: [p:up]
    cmd: docker compose --profile prod up --build -d {{.CLI_ARGS}}

  prod:down:
    desc: Stop production containers
    aliases: [p:down]
    cmd: docker compose --profile prod down {{.CLI_ARGS}}

  prod:logs:
    desc: View production logs
    aliases: [p:logs]
    cmd: docker compose --profile prod logs -f {{.CLI_ARGS}}

  prod:ps:
    desc: List production containers
    aliases: [p:ps]
    cmd: docker compose --profile prod ps

  prod:build:
    desc: Build Docker image
    aliases: [p:build]
    cmd: docker build -t {{.PROJECT_NAME}} -f Web.API/Dockerfile .
#endif

  # ============================================================================
  # Deploy (Non-Containerized - for VMs like EC2)
  # ============================================================================

  deploy:build:
    desc: Build self-contained deployment package
    aliases: [d:build]
    cmds:
      - dotnet publish {{.API_PROJECT}} -c Release -o {{.PUBLISH_DIR}} --self-contained -r {{.DEPLOY_RUNTIME}}
      - echo "Published to {{.PUBLISH_DIR}} for {{.DEPLOY_RUNTIME}}"

  deploy:build:fdd:
    desc: Build framework-dependent deployment (smaller, requires .NET on server)
    aliases: [d:build:fdd]
    cmds:
      - dotnet publish {{.API_PROJECT}} -c Release -o {{.PUBLISH_DIR}} --no-self-contained
      - echo "Published to {{.PUBLISH_DIR}} (framework-dependent)"

  deploy:package:
    desc: Create deployment tarball
    aliases: [d:package]
    platforms: [linux, darwin]
    deps: [deploy:build]
    cmds:
      - tar -czvf {{.PROJECT_NAME}}-{{.DEPLOY_RUNTIME}}.tar.gz -C {{.PUBLISH_DIR}} .
      - echo "Created {{.PROJECT_NAME}}-{{.DEPLOY_RUNTIME}}.tar.gz"

  deploy:package:windows:
    desc: Create deployment zip
    aliases: [d:package:windows]
    platforms: [windows]
    deps: [deploy:build]
    cmds:
      - powershell Compress-Archive -Path "{{.PUBLISH_DIR}}/*" -DestinationPath "{{.PROJECT_NAME}}-{{.DEPLOY_RUNTIME}}.zip" -Force
      - echo "Created {{.PROJECT_NAME}}-{{.DEPLOY_RUNTIME}}.zip"

  deploy:clean:
    desc: Clean publish directory
    aliases: [d:clean]
    cmds:
      - '{{if eq OS "windows"}}rmdir /s /q {{.PUBLISH_DIR}}{{else}}rm -rf {{.PUBLISH_DIR}}{{end}}'
    ignore_error: true

#if (IncludeTests)
  # ============================================================================
  # CI/CD Tasks (for GitHub Actions)
  # ============================================================================

  ci:restore:
    desc: "[CI] Restore dependencies"
    cmd: dotnet restore

  ci:build:
    desc: "[CI] Build for CI"
    cmd: dotnet build --no-restore --configuration Release

  ci:test:unit:
    desc: "[CI] Run unit tests"
    cmds:
      - dotnet test {{.TEST_DOMAIN}} --no-build --configuration Release --verbosity normal
      - dotnet test {{.TEST_APPLICATION}} --no-build --configuration Release --verbosity normal

  ci:test:integration:
    desc: "[CI] Run integration tests"
    cmd: dotnet test {{.TEST_INTEGRATION}} --no-build --configuration Release --verbosity normal

  ci:format:
    desc: "[CI] Check formatting"
    cmd: dotnet format --verify-no-changes
#endif

#if (IncludeExamples)
  # ============================================================================
  # Utilities
  # ============================================================================

  example:remove:
    desc: Remove Products example from solution
    platforms: [linux, darwin]
    cmd: ./scripts/remove-products-example.sh

  example:remove:windows:
    desc: Remove Products example from solution (Windows)
    platforms: [windows]
    cmd: powershell -ExecutionPolicy Bypass -File scripts/remove-products-example.ps1
#endif

  info:
    desc: Show environment info
    cmds:
      - dotnet --info
      - echo "---"
#if (IncludeDocker)
      - docker --version
      - docker compose version
#endif
    silent: true
